SELECT  ATK_ID AS ATK_CleanOrgID 
		,ATK_ID AS ATK_AirTrackingID
		,'01' AS ATK_SRCOrgID
		,TO_CHAR(ATK_AUDIT_CD, 'YYYYMMDD') AS ATK_DTDOrgID
    ,TO_CHAR(ATK_AUDIT_CD, 'HH24MI') AS ATK_DTMCleanOrgID
    ,ATKX_CHANNEL_NAME AS ATK_BCNCleanOrgID 
,0 as ATK_MemberFlag
,CASE WHEN ATK_STATUS IN ('N', 'C') THEN 1 else 0 end AS ATK_NonMemberFlag 
--,1 as ATK_NonMemberFlag

,ATK_DISCOUNT_BASE AS ATK_ValueOfTicket
,ATK_PRT_ID AS ATK_PRTCleanOrgID
,ATK_PRT_CODE  AS ATK_Designator
,ATKX_PRODUCT_NAME as ATK_TCTCleanOrgID
--,((CASE WHEN ATK_STATUS IN ('N', 'C') THEN 1 else 0 end)*(ATK_DISCOUNT_BASE)) as ATK_ValueOfNonMembers

,ATK_CURRENCY_CODE as ATK_CURCleanOrgID
,CASE WHEN CER_RATE IS NOT NULL THEN CER_RATE ELSE 1 END AS ATK_RATE
,CASE WHEN CER_CONVERSION_UNIT IS NOT NULL THEN CER_CONVERSION_UNIT ELSE 1 END AS ATK_Conversion_Unit
,ATK_DISCOUNT_BASE * (CASE WHEN CER_RATE IS NOT NULL THEN CER_RATE ELSE 1 END)/(CASE WHEN CER_CONVERSION_UNIT IS NOT NULL THEN CER_CONVERSION_UNIT ELSE 1 END) as ATK_ValueOfTicketNOK

,ATK_ORIGIN AS ATK_AIROriginCleanOrgID
,ATK_DESTINATION AS ATK_AIRDestCleanOrgID
,ATKX_SOLD_IN_LANGUAGE AS ATKX_SoldInLanguage
    
FROM TLT_AIR_TRACKING

  LEFT JOIN CMT_EXCHANGE_RATES --DLA DANYCH SPRZED 2016-12-20 NIE MAMY EXCHANGE RATES - NIE LICZY PRAWIDOWO!
    ON (ATK_CURRENCY_CODE=CER_CURRENCY_FROM
    and to_char(ATK_AUDIT_CD, 'yyyy-mm-dd')=to_char(CER_EFFECTIVE_DATE, 'yyyy-mm-dd'))
    AND CER_CURRENCY_TO = 'NOK'
WHERE
('<DateDailyFrom>' <= TO_CHAR(ATK_AUDIT_CD, 'YYYYMMDD') OR '<DateDailyFrom>' <= TO_CHAR(ATK_AUDIT_MD, 'YYYYMMDD'))
AND 
(TO_CHAR(ATK_AUDIT_CD, 'YYYYMMDD') < '<DateDailyTo>' OR TO_CHAR(ATK_AUDIT_MD, 'YYYYMMDD') < '<DateDailyTo>')
--AND 
--ATK_STATUS IN ('N', 'C')